spring.application.name=JOBTrackr
spring.datasource.url=jdbc:h2:mem:freelancerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
    jwt.secret=3q2+7w==kL9pQzYhFh3d3e8dLk2j3m4n5o6p7q8r9s0t1u2v3w4x5y6z7==
    jwt.expiration=86400000